version: "2.4"

services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.75.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - HONEYCOMB_API_KEY
      - HONEYCOMB_DATASET
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "55679:55679"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
      - zipkin
      -
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      - QUERY_LOOKBACK=157784630000
      - QUERY_LOG_LEVEL=DEBUG
      - JAVA_OPTS=-Xms256m -Xmx256m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    command: --logging.level.zipkin2=DEBUG

    postgresql:
      image: postgres:15.2
      environment:
        - POSTGRES_PASSWORD=postgres

# see https://www.jaegertracing.io/docs/1.8/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" #serve frontend
      - "14250:14250" #accept jaeger.thrift directly from clients
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000
