version: "2.4"

# noinspection ComposeUnknownKeys
x-common-env: &common-env
    HONEYCOMB_API_KEY: NgDVXmQ46ifGuZPz3fe5eQ
    HONEYCOMB_DATASET:
    HONEYCOMB_API: https://api.honeycomb.io/
    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
    OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317/
    OTEL_EXPORTER_OTLP_HEADERS:
    OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
    MESSAGE_ENDPOINT: message-java:9000
    NAME_ENDPOINT: name-java:8000
    YEAR_ENDPOINT: year-java:6001
    REDIS_URL: redis

services:
    frontend-java:
        build: ./java/frontend
        image: hnyexample/frontend-java
        environment:
            <<: *common-env
            OTEL_SERVICE_NAME: frontend-svc
        ports:
            - 7777:7777

    message-java:
        build: ./java/message-service
        image: hnyexample/message-java
        environment:
            <<: *common-env
            OTEL_SERVICE_NAME: message-svc
        ports:
            - 9000:9000

    name-java:
        build: ./java/name-service
        image: hnyexample/name-java
        environment:
            <<: *common-env
            OTEL_SERVICE_NAME: name-svc
        ports:
            - 8000:8000

    year-java:
        build: ./java/year-service
        image: hnyexample/year-java
        environment:
            <<: *common-env
            OTEL_SERVICE_NAME: year-svc
        ports:
            - 6001:6001

    numbers-kotlin:
        build: ./java/numbers
        image: hnyexample/numbers-java
        environment:
            <<: *common-env
            OTEL_SERVICE_NAME: numbers-kotlin
        ports:
            - 8080:8080
        external_links:
            - postgresql
            - collector
