receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        # CORS for browser communication
        cors:
          allowed_origins: "http://localhost:8080"

  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus


exporters:
  zipkin/zpk:
    endpoint: http://zipkin:9411/api/v2/spans
    tls:
      insecure: true
  jaeger:
    endpoint: http://jaeger:14250
    tls:
      insecure: true
  logging:
    loglevel: debug
  otlp/hny:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
  prometheus:
    endpoint: "0.0.0.0:8889"



service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [zipkin/zpk, jaeger, otlp/hny] # "logging" could be used for logging
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]