receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        # CORS for browser communication
        cors:
          allowed_origins: "http://localhost:8080"

processors:
  batch:

exporters:
  zipkin/zpk:
    endpoint: http://zipkin:9411/api/v2/spans
    tls:
      insecure: true
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    loglevel: debug
  otlp/hny:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin/zpk, jaeger, otlp/hny] # "logging" could be used for logging